version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: stylelint
        versions: [^15]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
